Cargo.lock, crd/Cargo.toml, examples/simple-nificluster.yaml, operator/Cargo.toml, operator/src/error.rs, operator/src/lib.rs, operator/src/monitoring.rs
- Split create_pod_and_config_maps into create_pod and create_config_maps
- Using operator-rs build_config_map and create_config_map
- Using operator-rs build_resource_name for pods and config maps.
- Bumped kube-rs to 0.58
Related: [10](https://github.com/stackabletech/issues/issues/10)
=> Adapted to operator-rs build_resource_name and create_config_map.

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/nifi-operator/crds/crds.yaml, rust/crd/src/lib.rs, rust/operator-binary/src/authentication.rs, rust/operator-binary/src/config.rs, rust/operator-binary/src/controller.rs
Fixes https://github.com/stackabletech/nifi-operator/issues/502.
Keytool is used to set a password for the PKCS12 stores, because NiFi complains when no password is specified:
```
WARN [main] o.a.nifi.security.util.SslContextFactory Some truststore properties are populated (/stackable/server_tls/truststore.p12, ********, PKCS12) but not valid
Failed to start web server: Invalid nifi.web.https configuration in nifi.properties
```
At least I could not make it work without a password for the store.
Local Kuttl test for LDAP with TLS worked fine.
Not sure about the naming of `STACKABLE_SERVER_TLS_DIR`, I just used the same name that was used in the change for trino-operator. Might not be appropiate for NiFi.
Also: I don't think we need the random destination alias (as implemented in …
=> Let secret-op handle pkcs12 stores

rust/operator-binary/src/controller.rs
NiFi 1.18 fails to start, because it can't read the contents of the PKCS12 truststore. Since https://github.com/stackabletech/nifi-operator/pull/505, secret-operator handles the creation of the PKCS12 key- and truststore. To create the encrypted truststore, we use the [p12 crate](https://docs.rs/p12/latest/p12/), which creates the PKCS12 store using a legacy algorithm. Currently, we can't use the openssl crate for this, see [this comment](https://github.com/stackabletech/secret-operator/blob/2aee67ec4279ee733eae03c2ce6e7febe4572c30/rust/operator-binary/src/format/convert.rs#L89-L93).
As a workaround, until secret-operator is able to create the PKCS12 truststore with AES-256-CBC encryption (right now the p12 crate uses RC2-40-CBC), we import the truststore using keytool (which is able to …
=> Use keytool to rewrite truststore with AES encryption

docs/modules/nifi/pages/usage_guide/external_ports.adoc, docs/modules/nifi/partials/nav.adoc
Adds documentation on how to expose processor ports outside of Kubernetes.
Fixes #317 
```[tasklist]
```
```[tasklist]
```
=> Fixes #317

docs/modules/nifi/examples/getting_started/test_getting_started_helm.sh
Commented out ExternalIP from helm callout as the json parsing does not work on e.g. kind
Stackablectl works fine.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Getting-started scripts - working helm script

CHANGELOG.md, Cargo.toml, deploy/helm/nifi-operator/crds/crds.yaml, docs/modules/nifi/pages/usage_guide/operations/graceful-shutdown.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/config.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/operations/graceful_shutdown.rs, rust/operator-binary/src/operations/mod.rs, tests/templates/kuttl/smoke/30-assert.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Support graceful shutdown

docs/modules/nifi/pages/usage_guide/resource-configuration.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(docs): Changed defaults documentation (23.7)

docs/modules/nifi/examples/getting_started/getting_started.sh, docs/modules/nifi/examples/getting_started/getting_started.sh.j2, docs/modules/nifi/pages/getting_started/first_steps.adoc
This updates the docs as pointed out by @sbernauer.
=> chore(docs): Update stackablectl commands in getting started guide

docs/modules/nifi/examples/getting_started/getting_started.sh, docs/modules/nifi/examples/getting_started/test-nifi.sh
* single pod for ZooKeeper (make the guide more lightweight)
* update ZooKeeper version to latest
* single pod for Nifi (fix random JWT validation failures and make the guide more lightweight)
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(docs): make the getting started guide run reliably

tests/release.yaml, tests/templates/kuttl/cluster_operation/00-patch-ns.yaml.j2, tests/templates/kuttl/ldap/00-patch-ns.yaml.j2, tests/templates/kuttl/logging/00-patch-ns.yaml.j2, tests/templates/kuttl/orphaned_resources/00-patch-ns.yaml.j2, tests/templates/kuttl/resources/00-patch-ns.yaml.j2, tests/templates/kuttl/smoke/00-patch-ns.yaml.j2, tests/templates/kuttl/upgrade/00-patch-ns.yaml.j2, tests/test-definition.yaml
Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (822.19s)
--- PASS: kuttl/harness/orphaned_resources_zookeeper-latest-3.9.1_nifi-1.25.0_openshift-true (205.65s)
--- PASS: kuttl/harness/ldap_zookeeper-latest-3.9.1_nifi-1.25.0_ldap-use-tls-true_openshift-true (241.52s)
--- PASS: kuttl/harness/cluster_operation_zookeeper-latest-3.9.1_nifi-latest-1.25.0_openshift-true (208.70s)
--- PASS: kuttl/harness/resources_zookeeper-latest-3.9.1_nifi-1.25.0_openshift-true (155.54s)
--- PASS: kuttl/harness/upgrade_zookeeper-latest-3.9.1_nifi_old-1.21.0_nifi_new-1.25.0_openshift-true (422.08s)
--- PASS: kuttl/harness/logging_zookeeper-latest-3.9.1_nifi-1.25.0_openshift-true (128.26s)
--- PASS: kuttl/harness/smoke_zookeeper-3.8.3_nifi-1.25.0_openshift-true_listener- …
```
=> tests: added namespace patch for openshift tests

CHANGELOG.md, tests/templates/kuttl/cluster_operation/20-install-nifi.yaml.j2, tests/templates/kuttl/cluster_operation/30-stop-nifi.yaml.j2, tests/templates/kuttl/cluster_operation/40-pause-nifi.yaml.j2, tests/templates/kuttl/cluster_operation/50-restart-nifi.yaml.j2, tests/templates/kuttl/ldap/12-install-nifi.yaml.j2, tests/templates/kuttl/logging/03-install-nifi.yaml.j2, tests/templates/kuttl/orphaned_resources/02-install-nifi.yaml.j2, tests/templates/kuttl/resources/02-install-nifi.yaml.j2, tests/templates/kuttl/smoke/30-install-nifi.yaml.j2, tests/templates/kuttl/upgrade/02-install-nifi.yaml.j2, tests/templates/kuttl/upgrade/05-assert.yaml.j2, tests/templates/kuttl/upgrade/05-upgrade-nifi.yaml.j2, tests/test-definition.yaml
This was done to be able to test : https://github.com/stackabletech/docker-images/pull/663 as seen in the `test-definition.yaml` comments.
:warning:  CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/nifi-operator-it-custom/55/
:green_circle:  Fixing and rerunning the **failed** CI tests individually:
```
$ ./scripts/run-tests --skip-release --test-suite openshift --skip-delete --test upgrade
...
--- PASS: kuttl (405.61s)
--- PASS: kuttl/harness/upgrade_zookeeper-latest-3.9.2_nifi_old-1.21.0_nifi_new-1.25.0,docker.stackable.tech_sandbox_nifi_1.25.0-stackable0.0.0-dev_openshift-true (394.15s)
PASS
```
:green_circle: And
```
$ ./scripts/run-tests --skip-release --test-suite openshift --skip-delete --test cluster_operation
...
--- PASS: …
```
=> feat: support custom images in integration tests

rust/operator-binary/src/reporting_task/mod.rs, tests/templates/kuttl/ldap/create_ldap_user.sh
The LDAP Bind DNs were changed, but not updated in the comments.
Since the new OU has a space, I have quoted all the DNs used in the commands.
=> chore: Update LDAP bind OU, add quotes to DNs

CHANGELOG.md, deploy/helm/nifi-operator/crds/crds.yaml, docs/modules/nifi/pages/usage_guide/security.adoc, rust/crd/src/lib.rs, rust/crd/src/tls.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/reporting_task/mod.rs, rust/operator-binary/src/security/mod.rs, rust/operator-binary/src/security/tls.rs
Fixes https://github.com/stackabletech/nifi-operator/issues/499
Alternate take on https://github.com/stackabletech/nifi-operator/pull/529, but a little bit more simplistic.
I also renamed `clusterConfig.tls.httpSecretClass` to `clusterConfig.tls.serverSecretClass` to be consistent with other operators (like zk or trino).
I skipped the whole "whether to request node certs" thing, as listener-op will replace it anyway.
```yaml
spec:
clusterConfig:
tls: # mandatory
serverSecretClass: non-default-secret-class # mandatory, defaults to tls
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Make https secretclass configurable

docs/modules/nifi/pages/usage_guide/resource-configuration.adoc
docs: remove home module from refs (stackabletech/documentation#637)
=> docs: remove home module from refs (stackabletech/documentation#637)

CHANGELOG.md, deploy/helm/nifi-operator/crds/crds.yaml, docs/modules/nifi/pages/usage_guide/security.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/controller.rs, tests/templates/kuttl/smoke/30-install-nifi.yaml.j2, tests/templates/kuttl/smoke/31-assert.yaml.j2
Allow adding proxy hosts that should be allowed by NiFi or turning the host header check off entirely.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Allow configuring NiFi proxy host behaviour

CHANGELOG.md, docs/modules/nifi/pages/usage_guide/updating.adoc, docs/modules/nifi/partials/supported-versions.adoc, rust/operator-binary/src/config.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/security/sensitive_key.rs, tests/templates/kuttl/upgrade/05-assert.yaml.j2, tests/templates/kuttl/upgrade/05-upgrade-nifi.yaml.j2, tests/templates/kuttl/upgrade/generate-and-log-flowfiles.xml, tests/test-definition.yaml
part of: <https://github.com/stackabletech/docker-images/issues/836>
https://stackable-workspace.slack.com/archives/C031NP72H7T/p1726502134517489
> The older flow.xml.gz format was deprecated as of Apache NiFi 1.16 in favor of the newer flow.json.gz format.   NiFi 1.16+ will only load the flow.xml.gz if the flow.json.gz does not already exist during startup.  Upon successful startup, NiFi will generate the flow.json.gz.  The NiFi 1.16+ version will still generate both the flow.xml.gz and flow.json.gz formats with every change made on the UI. 
> With the major release of Apache NiFi 2.x, the deprecated flow.xml.gz format was removed.
There is no option in NiFi 2.0 to support the older flow.xml.gz format.
- Not all of these items are applicable to all PRs, the author should update this …
=> fix: use flow.json.gz to easily migrate to version 2.0

docs/modules/nifi/partials/supported-versions.adoc
The docs build was broken because the `supported-versions.adoc` partial is included _outside_ the `nifi` module and then the xref didn't work anymore.
This is the fix.
=> fix: make xref work from ROOT module

CHANGELOG.md, deploy/helm/nifi-operator/crds/crds.yaml, docs/modules/nifi/pages/usage_guide/configuration-environment-overrides.adoc, docs/modules/nifi/pages/usage_guide/monitoring.adoc, rust/crd/src/lib.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/reporting_task/mod.rs
Closes https://github.com/stackabletech/nifi-operator/issues/689
For CRD change look at `deploy/helm/nifi-operator/crds/crds.yaml`
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Support disabling and podOverrides on the create-reporting-task Job

CHANGELOG.md, docs/modules/nifi/pages/usage_guide/updating.adoc, docs/modules/nifi/partials/supported-versions.adoc, examples/simple-nifi-cluster.yaml, tests/templates/kuttl/oidc/login.py, tests/test-definition.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Replace NiFi 2.0.0-M4 with 2.0.0

CHANGELOG.md, docs/modules/nifi/pages/usage_guide/monitoring.adoc, rust/operator-binary/src/controller.rs, rust/operator-binary/src/reporting_task/mod.rs, tests/templates/kuttl/smoke/60-assert.yaml.j2, tests/templates/kuttl/upgrade/04-assert.yaml.j2, tests/templates/kuttl/upgrade/07-assert.yaml.j2
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: Disable create-reporting-task for NiFi 2.x and document regression

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/operator-binary/Cargo.toml, rust/operator-binary/src/config.rs, rust/operator-binary/src/security/oidc.rs
Fixes https://github.com/stackabletech/nifi-operator/issues/716
Deploying nifi into the e2e-sec demo:
0.0.0-dev: `https://85.215.194.243:30584/realms/.well-known/openid-configuration` (obviously broken) => Caused by: org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"error":"Realm does not exist"}"
This PR: `https://85.215.194.243:30584/realms/demo/.well-known/openid-configuration` => Correct :heavy_check_mark: 
0.0.0-dev: `https://85.215.194.243:30584/realms/demo/.well-known/openid-configuration` => Correct :heavy_check_mark: 
This PR: `https://85.215.194.243:30584/realms/demo/.well-known/openid-configuration` => Correct :heavy_check_mark: 
- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes …
=> fix: Construction of OIDC endpoint when rootPath has no trailing slash

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/nifi-operator/crds/crds.yaml, rust/crd/src/lib.rs, rust/operator-binary/src/controller.rs, rust/operator-binary/src/reporting_task/mod.rs, rust/operator-binary/src/security/mod.rs, rust/operator-binary/src/security/tls.rs
Part of: https://github.com/stackabletech/issues/issues/586
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Support setting TLS certificate lifetimes

CHANGELOG.md, Cargo.lock, deploy/helm/nifi-operator/crds/crds.yaml, docs/modules/nifi/pages/usage_guide/index.adoc, docs/modules/nifi/pages/usage_guide/overrides.adoc, docs/modules/nifi/partials/nav.adoc, rust/crd/src/lib.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/config/jvm.rs, rust/operator-binary/src/config/mod.rs, rust/operator-binary/src/controller.rs
Part of https://github.com/stackabletech/issues/issues/584
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Support configuring JVM arguments

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/nifi-operator/crds/crds.yaml, deploy/helm/nifi-operator/values.yaml, docs/modules/nifi/pages/reference/environment-variables.adoc, docs/modules/nifi/pages/usage_guide/custom_processors.adoc, tests/templates/kuttl/ldap/03-install-test-nifi.yaml, tests/templates/kuttl/logging/05-install-nifi-test-runner.yaml, tests/templates/kuttl/oidc/20-login-test.yaml.j2, tests/templates/kuttl/smoke/50-install-test-nifi.yaml, tests/templates/kuttl/upgrade/03-install-test-nifi.yaml, tests/test-definition.yaml
```
--- PASS: kuttl (1608.37s)
--- PASS: kuttl/harness/oidc_zookeeper-latest-3.9.2_nifi-2.0.0_oidc-use-tls-true_openshift-false (98.64s)
--- PASS: kuttl/harness/smoke_zookeeper-3.9.2_nifi-1.27.0_openshift-false_listener-class-cluster-internal (247.56s)
--- PASS: kuttl/harness/ldap_zookeeper-latest-3.9.2_nifi-1.27.0_ldap-use-tls-false_openshift-false (181.03s)
--- PASS: kuttl/harness/ldap_zookeeper-latest-3.9.2_nifi-2.0.0_ldap-use-tls-true_openshift-false (173.46s)
--- PASS: kuttl/harness/upgrade_zookeeper-latest-3.9.2_nifi_old-1.27.0_nifi_new-2.0.0_openshift-false (366.96s)
--- PASS: kuttl/harness/ldap_zookeeper-latest-3.9.2_nifi-2.0.0_ldap-use-tls-false_openshift-false (179.40s)
--- PASS: kuttl/harness/orphaned_resources_zookeeper-latest-3.9.2_nifi-1.27.0_o …
```
=> chore: add oci references, merge templating changes

docs/modules/nifi/examples/getting_started/getting_started.sh, docs/modules/nifi/examples/getting_started/getting_started.sh.j2, docs/modules/nifi/examples/getting_started/test-nifi.sh, docs/modules/nifi/partials/supported-versions.adoc, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/966.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Bump versions to 1.28.1 and 2.2.0

docs/modules/nifi/pages/usage_guide/writing-to-iceberg-tables.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Mention Iceberg support removal

docs/modules/nifi/examples/getting_started/getting_started.sh, docs/modules/nifi/examples/getting_started/getting_started.sh.j2, docs/modules/nifi/partials/supported-versions.adoc
Part of https://github.com/stackabletech/docker-images/issues/966.
It was decided that NiFi 2.x will remainin experimental in SDP 25.3, until there is a way to handle restoring templates/flows.
=> docs: Revert to 1.28.1

docs/modules/nifi/pages/troubleshooting/index.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Add troubleshooting guide on Ingress problems

docs/modules/nifi/examples/getting_started/getting_started.sh, docs/modules/nifi/examples/getting_started/getting_started.sh.j2, docs/modules/nifi/pages/getting_started/installation.adoc, docs/templating_vars.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Update helm install commands

CHANGELOG.md, tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1) in tests
=> test: Bump vector to 0.46.1

docs/modules/nifi/pages/usage_guide/updating.adoc, docs/modules/nifi/partials/supported-versions.adoc, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1079.
- Add: `2.4.0`
- Remove: `2.2.0`
=> chore: Add NiFi 2.4.0 and remove 2.2.0

tests/templates/kuttl/iceberg/50_nifi.yaml.j2
Part of https://github.com/stackabletech/nifi-operator/issues/737
=> test: Switch Iceberg test to not use Zookeeper

CHANGELOG.md, rust/operator-binary/src/controller.rs, rust/operator-binary/src/reporting_task/mod.rs
Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details
=> chore: Remove hardcoded uid and gid

CHANGELOG.md, rust/operator-binary/src/controller.rs, rust/operator-binary/src/service.rs, tests/templates/kuttl/external-access/30-assert.yaml
- Add metrics service for NiFi v2 as well
This is according to 3.1 from https://github.com/stackabletech/decisions/issues/51
=> Add metrics service for nifi v2

CHANGELOG.md, docs/modules/nifi/pages/usage_guide/monitoring.adoc, rust/operator-binary/src/controller.rs, rust/operator-binary/src/reporting_task/mod.rs, rust/operator-binary/src/security/mod.rs, rust/operator-binary/src/security/tls.rs, tests/templates/kuttl/iceberg/60_nifi-flow-with-kerberos.json, tests/templates/kuttl/iceberg/60_nifi-flow-without-kerberos.json, tests/templates/kuttl/iceberg/README.md, tests/templates/kuttl/smoke_v1/test_nifi_metrics.py, tests/templates/kuttl/upgrade/test_nifi_metrics.py
The reporting task (nifi 1 only) mounted a wrong secret-operator volume, fixed this.
Also, lot's of random test fixes needed
=> chore: Fix tests, partially by fixing reporting-task

Cargo.lock, Cargo.nix, Cargo.toml, rust/operator-binary/src/controller.rs
~~During reconciliation the moved code from the PR was called after `pod_builder.add_container(container_nifi.build())`, therefore not updating the volumeMounts of the `nifi` container with the volumeMounts related to the authentication config and they were missing. This PR adds them in.~~
After talking with @sbernauer: The prepare container was configuring things with the auth configs being mounted, so the code/tests still worked as expected.
But hence the volumeMounts are not needed on the nifi container (which weren't applied anyway due to the crossed out explanation above). The correct way would be to remove the ContainerBuilder from the mounting step.
Adjusted the code to reflect that, also renamed and dropped the ContainerBuilder for code clarity. Will run integrationtests to make …
=> refactor: Don't modify ContainerBuilder after it has been build

CHANGELOG.md, rust/operator-binary/src/controller.rs, rust/operator-binary/src/security/authentication.rs, tests/templates/kuttl/external-access/30-assert.yaml, tests/templates/kuttl/ldap/03-assert.yaml, tests/templates/kuttl/smoke_v1/50-assert.yaml, tests/templates/kuttl/smoke_v2/50-assert.yaml, tests/templates/kuttl/upgrade/03-assert.yaml
Part of https://github.com/stackabletech/issues/issues/764.
The server TLS truststore handling was actually fine and left as-is. Only LDAP and OIDC ca cert handling was affected.
=> fix: Prevent missing certificates

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/nifi-operator/crds/crds.yaml, rust/operator-binary/src/main.rs
This reverts commit 66154109a38d3e4650dfcdec8b8511957925a0f8. (PR https://github.com/stackabletech/nifi-operator/pull/852)
With https://github.com/stackabletech/nifi-operator/pull/852 the `kube-rs` version was transitively bumped, which led to bugs in the CRD generation. @sbernauer will work on an upstream fix, then this revert can be reverted again later.
=> Revert "feat: Add EoS checker (#852)"
