.github/dependabot.yml
.github/workflows/rust.yml
CHANGELOG.md
Cargo.lock
README.adoc
crd/Cargo.toml
crd/src/bin/generate_crds.rs
deny.toml
operator/Cargo.toml
operator/src/lib.rs
server/Cargo.toml
server/build.rs
server/src/main.rs

This PR is part of a chain of PRs across all our projects to make them as consistent as possible in preparation for our first release.
Things it can contain (not all might be applicable to all repositories):
- Added CLI handling
- Cargo.toml
- Add repository key
- Set version properly
- Sort keys
- deny.toml consistency
- Pull request template
- Github CI consistency (e.g. rustdoc)
- cargo update
- Dependabot does not ignore stackable components anymore
- Adds changelog & readme
- Correct license
Fixes [61](https://github.com/stackabletech/nifi-operator/issues/61)

Product updates and CLI handling

---

Cargo.lock
crd/Cargo.toml
operator/Cargo.toml
server/Cargo.toml

Switched to tags.

---

CHANGELOG.md
Cargo.lock
deploy/crd/nificluster.crd.yaml
rust/crd/Cargo.toml
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator/Cargo.toml
rust/operator/src/lib.rs

Implemented versioning from operator-rs.

---

CHANGELOG.md
Cargo.lock
deploy/crd/nificluster.crd.yaml
rust/crd/Cargo.toml
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/stackable-nifi-operator.rs
rust/operator/Cargo.toml
rust/operator/src/lib.rs
rust/operator/src/monitoring.rs

Adapted to kube-rs 0.60 and operator-rs 0.2.2

---

CHANGELOG.md
Cargo.lock
deploy/crd/nificluster.crd.yaml
rust/crd/Cargo.toml
rust/crd/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator/Cargo.toml
rust/operator/src/lib.rs

Use sticky scheduler.

---

CHANGELOG.md
Cargo.lock
README.adoc
docs/modules/ROOT/pages/dependencies.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/usage.adoc
examples/simple-nifi-service.yaml
examples/simple-nificluster.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml
rust/operator/Cargo.toml
rust/operator/src/lib.rs

fixes https://github.com/stackabletech/nifi-operator/issues/94

Adapt to docker image

---

CHANGELOG.md
Cargo.lock
deploy/helm/nifi-operator/Chart.yaml
deploy/manifests/configmap.yaml
deploy/manifests/deployment.yaml
deploy/manifests/serviceaccount.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml
rust/operator/Cargo.toml

Release 0.4.0. DO NOT SQUASH MERGE!

Release 0.4.0

---

bors.toml

Bors: Do not squash merge commits

---

docs/modules/ROOT/pages/configuration.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/partials/supported-versions.adoc

fixes https://github.com/stackabletech/nifi-operator/issues/117
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Document supported product versions

---

CHANGELOG.md
Cargo.lock
deploy/helm/nifi-operator/Chart.yaml
deploy/manifests/configmap.yaml
deploy/manifests/deployment.yaml
deploy/manifests/serviceaccount.yaml
docs/antora.yml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml

release 0.8.0

---

Cargo.lock
deploy/helm/nifi-operator/Chart.yaml
deploy/manifests/configmap.yaml
deploy/manifests/deployment.yaml
deploy/manifests/serviceaccount.yaml
docs/antora.yml
docs/modules/getting_started/examples/code/getting-started.sh
docs/modules/getting_started/examples/code/install-operator-output.txt
docs/templating_vars.yaml
rust/crd/Cargo.toml
rust/operator-binary/Cargo.toml

bump version 0.9.0-nightly

---

docs/modules/nifi/pages/usage_guide/extra_volumes.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

fixed incorrect syntax

---

CHANGELOG.md
deploy/helm/nifi-operator/crds/crds.yaml
rust/crd/src/lib.rs

cherry picked from commit 8d6f3e4b415f25d4e7923a163d29a24066ffa580
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Add missing crd defaults to 23.4

---

CHANGELOG.md
tests/kuttl-test.yaml.jinja2
tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml
tests/templates/kuttl/logging/nifi-vector-aggregator-values.yaml.j2
tests/templates/kuttl/logging/test_log_aggregation.py

Upgrade vector
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade vector

---

CHANGELOG.md
deploy/config-spec/properties.yaml
deploy/helm/nifi-operator/configs/properties.yaml
docs/modules/nifi/pages/usage_guide/configuration-environment-overrides.adoc
rust/operator-binary/src/config.rs
rust/operator-binary/src/controller.rs

CI: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/nifi-operator-it-custom/39/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

JVM config overrides

---

deploy/helm/nifi-operator/crds/crds.yaml
docs/modules/nifi/pages/usage_guide/listenerclass.adoc
docs/modules/nifi/partials/nav.adoc
rust/crd/src/lib.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

ListenerClass docs

---

docs/modules/nifi/pages/getting_started/installation.adoc
docs/modules/nifi/pages/index.adoc

Part of https://github.com/stackabletech/stackable-cockpit/pull/101

docs: Update references

---

docs/modules/nifi/pages/usage_guide/index.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Fix links

---

Cargo.lock
Cargo.toml
rust/operator-binary/Cargo.toml
rust/operator-binary/src/config.rs
rust/operator-binary/src/controller.rs

Part of https://github.com/stackabletech/product-config/issues/95

refactor: Use updated product-config

---

tests/templates/kuttl/cluster_operation/10-install-zk.yaml.j2
tests/templates/kuttl/ldap/10-install-zk.yaml.j2
tests/templates/kuttl/logging/02-install-zookeeper.yaml.j2
tests/templates/kuttl/orphaned_resources/01-install-zk.yaml.j2
tests/templates/kuttl/resources/01-install-zk.yaml.j2
tests/templates/kuttl/smoke/20-install-zk.yaml.j2
tests/templates/kuttl/upgrade/01-install-zk.yaml.j2

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Fix zk crd changes in integration tests

---

docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/getting_started.sh.j2
docs/modules/nifi/examples/getting_started/install-operator-output.txt
docs/modules/nifi/examples/getting_started/install-operator-output.txt.j2
docs/modules/nifi/pages/getting_started/installation.adoc
docs/templating_vars.yaml

The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
```[tasklist]
```
```[tasklist]
```

docs: Add listener-operator where missing

---

CHANGELOG.md
Cargo.lock
Cargo.toml
deploy/helm/nifi-operator/crds/crds.yaml
rust/crd/src/authentication.rs
rust/crd/src/lib.rs
rust/operator-binary/src/main.rs

Better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Better CRD docs

---

docs/modules/nifi/pages/usage_guide/resource-configuration.adoc

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(docs): Changed defaults documentation (23.11)

---

Cargo.lock
Cargo.toml
deploy/helm/nifi-operator/crds/crds.yaml
rust/crd/src/affinity.rs
rust/crd/src/authentication.rs
rust/crd/src/lib.rs
rust/operator-binary/src/authentication.rs
rust/operator-binary/src/controller.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Chore: bump operator rs 0.60

---

CHANGELOG.md
deploy/helm/nifi-operator/templates/_helpers.tpl
deploy/helm/nifi-operator/templates/deployment.yaml
deploy/helm/nifi-operator/templates/roles.yaml
deploy/helm/nifi-operator/values.yaml

Part of: https://github.com/stackabletech/issues/issues/501

feat(helm): support labels in values.yaml

---

docs/modules/nifi/pages/usage_guide/updating.adoc

- removed left over selector in update docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Remove deprecated selector from docs

---

docs/modules/nifi/pages/usage_guide/monitoring.adoc

fixes #562 
```[tasklist]
```
```[tasklist]
```

Docs: document that the reporting task needs access to NiFi to run

---

deploy/helm/nifi-operator/values.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add Stackable vendor label to default values.yaml

---

tests/templates/kuttl/resources/02-assert.yaml.j2

Increase the timeout in the resources test
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Increase the timeout in the resources test

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
docs/modules/nifi/pages/usage_guide/writing-to-iceberg-tables.adoc
tests/templates/kuttl/upgrade/05-assert.yaml.j2

Part of https://github.com/stackabletech/issues/issues/601, https://github.com/stackabletech/issues/issues/557
```[tasklist]
```

chore: Bump stackable-operator and product-config

---

tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml

Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Use Vector Helm chart version 0.34.0 in the logging test

---

docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/getting_started.sh.j2
docs/modules/nifi/examples/getting_started/install-operator-output.txt
docs/modules/nifi/examples/getting_started/install-operator-output.txt.j2
docs/modules/nifi/examples/getting_started/test-nifi.sh

docs(getting-started): update stackablectl op install output

---

tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml

Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```

chore: Bump Vector to 0.40.0

---

deploy/helm/nifi-operator/templates/roles.yaml

See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(helm): use same scc as olm

---

docs/modules/nifi/partials/supported-versions.adoc

Part of https://github.com/stackabletech/issues/issues/623
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Backport 2.0.0 upgrade notes to 24.7 release

---

CHANGELOG.md
docs/modules/nifi/pages/usage_guide/updating.adoc
docs/modules/nifi/partials/supported-versions.adoc
tests/test-definition.yaml

Part of https://github.com/stackabletech/issues/issues/623
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update supported product versions and add 2.0.0 upgrade note

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
tests/templates/kuttl/smoke/30-install-nifi.yaml.j2
tests/templates/kuttl/smoke/31-assert.yaml

Part of: https://github.com/stackabletech/issues/issues/548
:green_circle: Test
```
$ ./scripts/run-tests --test-suite smoke-latest
...
--- PASS: kuttl (277.13s)
--- PASS: kuttl/harness/smoke_zookeeper-3.8.4_nifi-2.0.0-M4_openshift-false_listener-class-external-unstable (276.53s)
PASS
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(test): smoke testing env and config overrides

---

tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml

Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Upgrade the Vector aggregator in the logging tests

---

Cargo.lock
Cargo.toml
deploy/helm/nifi-operator/crds/crds.yaml
rust/operator-binary/src/controller.rs
rust/operator-binary/src/security/authentication.rs

part of: https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: bump op-rs

---

tests/templates/kuttl/oidc/login.py

Fix for custom images in OIDC test

Fix for custom images in OIDC test

---

tests/templates/kuttl/cluster_operation/20-install-nifi.yaml.j2
tests/templates/kuttl/cluster_operation/30-stop-nifi.yaml.j2
tests/templates/kuttl/cluster_operation/40-pause-nifi.yaml.j2
tests/templates/kuttl/cluster_operation/50-restart-nifi.yaml.j2
tests/templates/kuttl/ldap/10-install-zk.yaml.j2
tests/templates/kuttl/ldap/12-install-nifi.yaml.j2
tests/templates/kuttl/logging/02-install-zookeeper.yaml.j2
tests/templates/kuttl/logging/04-install-nifi.yaml.j2
tests/templates/kuttl/oidc/10-install-zk.yaml.j2
tests/templates/kuttl/orphaned_resources/01-install-zk.yaml.j2
tests/templates/kuttl/orphaned_resources/02-install-nifi.yaml.j2
tests/templates/kuttl/resources/01-install-zk.yaml.j2
tests/templates/kuttl/resources/02-install-nifi.yaml.j2
tests/templates/kuttl/upgrade/01-install-zk.yaml.j2
tests/templates/kuttl/upgrade/02-install-nifi.yaml.j2

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

test: add shutdown timeout

---

CHANGELOG.md
Cargo.nix
crate-hashes.json
rust/operator-binary/src/config.rs

Fixup of https://github.com/stackabletech/nifi-operator/pull/686
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: Fix typo in OIDC truststore strategy

---

docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/install_output.txt

Part of https://github.com/stackabletech/issues/issues/647.

docs: Update release in getting_started

---

docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/getting_started.sh.j2

Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/nifi-operator/pull/714.

chore(getting_started): Replace templating instructions with make

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/nifi-operator/Chart.yaml
docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1-rc2

---

tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml

Part of https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update Vector to 0.43.1 in integration tests

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/nifi-operator/templates/roles.yaml
rust/operator-binary/Cargo.toml
rust/operator-binary/src/controller.rs
rust/operator-binary/src/main.rs

Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```

chore: Update to operator-rs 0.84.1

---

docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/getting_started.sh.j2
examples/simple-nifi-cluster.yaml
tests/test-definition.yaml

Part of https://github.com/stackabletech/docker-images/issues/1020

chore: Update ZooKeeper to 3.9.3 pre-25.3.0

---

tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml

Part of: https://github.com/stackabletech/docker-images/issues/1146

chore: bump vector chart to 0.43.0

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/nifi-operator/Chart.yaml
deploy/helm/nifi-operator/crds/crds.yaml
docs/antora.yml
docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.7.0-rc1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/nifi-operator/Chart.yaml
docs/modules/nifi/examples/getting_started/getting_started.sh
docs/modules/nifi/examples/getting_started/install_output.txt
docs/templating_vars.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.7.0

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/controller.rs
rust/operator-binary/src/crd/mod.rs
rust/operator-binary/src/main.rs
rust/operator-binary/src/reporting_task/mod.rs
rust/operator-binary/src/security/mod.rs
rust/operator-binary/src/security/tls.rs

Part of https://github.com/stackabletech/issues/issues/762

chore: Update to stackable-operator 0.95.0

---

tests/templates/kuttl/logging/01-install-nifi-vector-aggregator.yaml

Part of https://github.com/stackabletech/docker-images/issues/1233
```
--- PASS: kuttl (652.11s)
--- PASS: kuttl/harness/logging_nifi-2.4.0_zookeeper-latest-3.9.3_openshift-false (343.49s)
--- PASS: kuttl/harness/logging_nifi-1.27.0_zookeeper-latest-3.9.3_openshift-false (429.60s)
--- PASS: kuttl/harness/logging_nifi-1.28.1_zookeeper-latest-3.9.3_openshift-false (308.61s)
PASS
```

chore: Bump vector version for 25.11.0
